---
summary: Build the Relay API server.

description: |
  The `build` task compiles the API server, dropping the
  binary in the `build` directory.

  This task runs in a Linux container. If working on Mac OS
  make sure to set GOOS appropriately.

image: relay-dev

command: go build -o build/relay-api-server -v ./cmd/api-server

arguments:
  GOOS:
    description: Platform to build for.
    default: linux

