---
summary: Build the Relay CI runner.

description: |
  The `build-runlet` task builds the runlet, which is Relay's
  CI task runner, and drops it in the `build` directory.

  This task runs in a Linux container. If working on Mac OS
  make sure to set GOOS appropriately.

image: relay-dev

command: go build -o build/runlet -v ./cmd/runlet

arguments:
  GOOS:
    description: Platform to build for.
    default: linux
